steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'me-central2-docker.pkg.dev/analog-sum-429419-u7/gke-cicd/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'me-central2-docker.pkg.dev//gke-cicd/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'me-central2-docker.pkg.dev/analog-sum-429419-u7/gke-cicd/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'me-central2-docker.pkg.dev/analog-sum-429419-u7/gke-cicd/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'me-central2-docker.pkg.dev//gke-cicd/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'me-central2-docker.pkg.dev/analog-sum-429419-u7/gke-cicd/flask-image' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=me-central2
    gcloud deploy apply --file deploy/dev.yaml --region=me-central2
    gcloud deploy apply --file deploy/prod.yaml --region=me-central2

    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=me-central2 --skaffold-file=skaffold.yaml

options:
  logging: CLOUD_LOGGING_ONLY
